name: tarea3.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Contruir la imagen
      run: docker build -t ghcr.io/alexander738022/proyecto:3.0.0 .

    - name: Login hacia Github Container Registry
      run: echo "${{ secrets.TOKEN_AV }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Push de la imagen a Github Container Registry
      run: docker push ghcr.io/alexander738022/proyecto:3.0.0